# asr_core.py — توافق خلفي: إعادة تصدير من حزمة asr
from asr import (
    DEFAULT_MODEL,
    MODEL_CHOICES,
    OUTPUTS_DIR,
    MODELS_DIR,
    SPK_DIR,
    _HAS_CUDA,
    get_model,
    run_asr,
    diarize_with_pyannote,
    load_enrolled,
    get_speaker_files,
    delete_speaker,
    enroll_voice,
    segments_to_srt,
    segments_to_vtt,
    process,
    process_many,
    cleanup_temp_files,
    to_wav16k,
    to_wav16k_enhanced,
    enhance_audio,
)
import asr.diarization as _diarization_mod

_PYANNOTE_AVAILABLE = getattr(_diarization_mod, "_PYANNOTE_AVAILABLE", False)

__all__ = [
    "DEFAULT_MODEL",
    "MODEL_CHOICES",
    "OUTPUTS_DIR",
    "MODELS_DIR",
    "SPK_DIR",
    "_HAS_CUDA",
    "_PYANNOTE_AVAILABLE",
    "get_model",
    "run_asr",
    "diarize_with_pyannote",
    "load_enrolled",
    "get_speaker_files",
    "delete_speaker",
    "enroll_voice",
    "segments_to_srt",
    "segments_to_vtt",
    "process",
    "process_many",
    "cleanup_temp_files",
    "to_wav16k",
    "to_wav16k_enhanced",
    "enhance_audio",
]
