#!/usr/bin/env bash
# Create or refresh local .env files from examples (development defaults).
set -euo pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root_dir"

force=0
if [[ "${1:-}" == "--force" ]]; then
  force=1
fi

log() { printf '[setup_env] %s\n' "$1"; }

gen_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    python3 -c "import secrets; print(secrets.token_hex(32))"
  fi
}

detect_whisper_device() {
  local py=""
  for candidate in "$root_dir/.venv/bin/python" "$root_dir/venv/bin/python" python3; do
    if [[ -x "$candidate" ]] || command -v "$candidate" >/dev/null 2>&1; then
      py="$candidate"
      break
    fi
  done
  if [[ -n "$py" ]] && "$py" - <<'PY' >/dev/null 2>&1
import torch
raise SystemExit(0 if torch.cuda.is_available() else 1)
PY
  then
    printf 'cuda'
  else
    printf 'cpu'
  fi
}

has_mishkal() {
  local py=""
  for candidate in "$root_dir/.venv/bin/python" "$root_dir/venv/bin/python" python3; do
    if [[ -x "$candidate" ]] || command -v "$candidate" >/dev/null 2>&1; then
      if "$candidate" -c "import mishkal" >/dev/null 2>&1; then
        return 0
      fi
    fi
  done
  return 1
}

write_if_allowed() {
  local dest="$1"
  if [[ -f "$dest" && "$force" -ne 1 ]]; then
    log "exists (skip): $dest — use --force to overwrite"
    return 0
  fi
  printf '%s' "$2" > "$dest"
  log "wrote: $dest"
}

whisper_device="$(detect_whisper_device)"
log "detected WHISPER_DEVICE=$whisper_device"

jwt_secret="$(gen_secret)"
tts_diacritize=0
if has_mishkal; then
  tts_diacritize=1
  log "mishkal found — enabling TTS_DIACRITIZE=1"
fi

omnivoice_bin="$root_dir/.tools/omnivoice/.venv/bin/omnivoice-infer"
omnivoice_line="# OMNIVOICE_INFER_BIN=.tools/omnivoice/.venv/bin/omnivoice-infer"
if [[ -x "$omnivoice_bin" ]]; then
  omnivoice_line="OMNIVOICE_INFER_BIN=.tools/omnivoice/.venv/bin/omnivoice-infer"
  log "OmniVoice CLI found — setting OMNIVOICE_INFER_BIN"
fi

root_env="$(cat <<EOF
# Generated by scripts/setup_env.sh — used by docker-compose*.yml
ASR_ENV=development
API_TOKEN=
BASE_URL=http://127.0.0.1:8000
ASR_ALLOWED_ORIGINS=http://127.0.0.1:8000,http://localhost:8000
MAX_UPLOAD_MB=50
ASR_DATA_DIR=data
ASR_WARMUP=0
LOG_LEVEL=INFO

WHISPER_MODEL=heavy
WHISPER_DEVICE=${whisper_device}
WHISPER_COMPUTE=float16
GPU_ID=0
ENHANCE_MODE=off
ENHANCE_LEVEL=strong
ASR_LOG_LOAD=1
FFMPEG_PATH=

SUMMARIZER_MODEL=data/models/summarizers/mT5_XLSum
ULTRA_MODEL=inceptionai/jais-13b-chat
ULTRA_4BIT=1
ULTRA_TRUST_REMOTE=1
ULTRA_PROMPT_MODE=auto
ULTRA_ALLOW_DOWNLOAD=1
HF_DEVICE_ID=-1
SUM_MAX_INPUT_TOKENS=800
SUM_MAX_PARTS=8
PUNCT_MODEL=data/models/punctuation/arabic_punct
NER_MODEL=data/models/ner/arabic_ner

RAG_ENABLE=0
RAG_EMB_MODEL=data/models/multilingual-e5-base
RAG_CHUNK_SIZE=1000
RAG_CHUNK_OVERLAP=150
RAG_BATCH=64
RAG_CHECK_EVERY=5000
RAG_USE_GPU=auto

TTS_PREPROCESS_ENABLED=1
TTS_MMS_ENABLED=1
TTS_DIACRITIZE=${tts_diacritize}
OMNIVOICE_TIMEOUT_SEC=14400

HF_TOKEN=
DOWNLOAD_RETRY_FOREVER=1
DOWNLOAD_RETRY_BASE_SEC=5
DOWNLOAD_RETRY_MAX_SEC=60
DOWNLOAD_MAX_WORKERS=1

JWT_SECRET=${jwt_secret}
JWT_EXPIRES_SECONDS=86400
JWT_ISSUER=meet-asr
JWT_AUDIENCE=meet-asr-api
ADMIN_EMAILS=admin@local

OUTPUTS_MAX_GB=10
CLEANUP_ENABLED=1
CLEANUP_MAX_AGE_HOURS=72
CLEANUP_INTERVAL_HOURS=24
TFIDF_MAX_ROWS=140000

TRANSCRIBE_MAX_QUEUED=20
TRANSCRIBE_MAX_CONCURRENT=2

TRANSFORMERS_VERBOSITY=error
EOF
)"

api_env="$(cat <<EOF
# Generated by scripts/setup_env.sh — loaded by apps/api/app/config.py
# Paths are relative to the project root (meet-asr/), NOT apps/api/
ASR_DATA_DIR=data
ASR_ENV=development
API_TOKEN=
BASE_URL=http://127.0.0.1:8000
ASR_ALLOWED_ORIGINS=http://127.0.0.1:8000,http://localhost:8000
MAX_UPLOAD_MB=50
LOG_LEVEL=INFO

ASR_WARMUP=0
WHISPER_MODEL=heavy
WHISPER_DEVICE=${whisper_device}
WHISPER_COMPUTE=float16
GPU_ID=0
ENHANCE_MODE=off
ENHANCE_LEVEL=strong
ASR_LOG_LOAD=1
FFMPEG_PATH=

TTS_PREPROCESS_ENABLED=1
TTS_MMS_ENABLED=1
TTS_DIACRITIZE=${tts_diacritize}
OMNIVOICE_TIMEOUT_SEC=14400
${omnivoice_line}

SUMMARIZER_MODEL=data/models/summarizers/mT5_XLSum
ULTRA_MODEL=inceptionai/jais-13b-chat
ULTRA_4BIT=1
ULTRA_TRUST_REMOTE=1
ULTRA_PROMPT_MODE=auto
ULTRA_ALLOW_DOWNLOAD=1
HF_DEVICE_ID=-1
SUM_MAX_INPUT_TOKENS=800
SUM_MAX_PARTS=8
PUNCT_MODEL=data/models/punctuation/arabic_punct
NER_MODEL=data/models/ner/arabic_ner

RAG_ENABLE=0
RAG_EMB_MODEL=data/models/multilingual-e5-base
RAG_CHUNK_SIZE=1000
RAG_CHUNK_OVERLAP=150
RAG_BATCH=64
RAG_CHECK_EVERY=5000
RAG_USE_GPU=auto

HF_TOKEN=
DOWNLOAD_RETRY_FOREVER=1
DOWNLOAD_RETRY_BASE_SEC=5
DOWNLOAD_RETRY_MAX_SEC=60
DOWNLOAD_MAX_WORKERS=1

JWT_SECRET=${jwt_secret}
JWT_EXPIRES_SECONDS=86400
JWT_ISSUER=meet-asr
JWT_AUDIENCE=meet-asr-api
ADMIN_EMAILS=admin@local

OUTPUTS_MAX_GB=10
CLEANUP_ENABLED=1
CLEANUP_MAX_AGE_HOURS=72
CLEANUP_INTERVAL_HOURS=24
TFIDF_MAX_ROWS=140000

TRANSCRIBE_MAX_QUEUED=20
TRANSCRIBE_MAX_CONCURRENT=2

TRANSFORMERS_VERBOSITY=error
EOF
)"

write_if_allowed "$root_dir/.env" "$root_env"
write_if_allowed "$root_dir/apps/api/.env" "$api_env"

log "Done. Restart the server: ./run.sh"
if [[ "$force" -ne 1 ]]; then
  log "Tip: ./scripts/setup_env.sh --force to regenerate JWT_SECRET"
fi
